import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Cart from "@/components/Cart/Cart";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="relative flex flex-col min-h-screen ">
          <Navbar />
          {/* <div className="absolute h-full w-full top-0 z-50 right-0 bg-white/30	backdrop-blur-sm ">
          </div>
          <Cart /> */}
          <div className="flex-grow flex-1">{children}</div>
        </main>
      </body>
    </html>
  );
}
